spring:
  application:
    name: customer-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 828126

server:
  compression:
    enabled: true
    mime-types: application/json
  port: 6060
  http2:
    enabled: true
logging:
  level:
    root: debug
